import {StyleSheet} from 'react-native';
import {verticalScale, horizontalScale, fontScale} from '../../Utils/ScaleSize';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  topView: {
    width: '100%',
    height: verticalScale(85),
    backgroundColor: '#f6f6f6',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  deliverView: {
    marginLeft: verticalScale(30),
  },
  deliverText: {
    fontFamily: 'Poppins-Regular',
    fontSize: verticalScale(13),
    color: '#a7a7a6',
  },
  mapsView: {
    flexDirection: 'row',
    width: horizontalScale(300),
    alignItems: 'center',
    gap: horizontalScale(10),
  },
  mapsText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: fontScale(13),
  },
  toggleText: {
    color: 'black',
    fontSize: verticalScale(14),
    transform: [{rotate: '90deg'}],
  },
  bellIconStyle: {
    position: 'absolute',
    alignSelf: 'flex-end',
    right: horizontalScale(30),
    width: horizontalScale(45),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    height: verticalScale(45),
    backgroundColor: 'white',
  },
  inputFilterView: {
    width: '100%',
    height: verticalScale(95),
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.2,
    shadowRadius: 0,
    elevation: 5,
  },
  inputFilterInsideView: {
    flexDirection: 'row',
    gap: horizontalScale(15),
  },
  inputTextStyle: {
    padding: 10,
    paddingHorizontal: horizontalScale(70),
    fontFamily: 'Poppins-Regular',
    lineHeight: 10,
    fontSize: verticalScale(15),
    backgroundColor: '#f6f6f6',
    color: 'black',
    width: horizontalScale(300),
    height: verticalScale(50),
    borderRadius: 10,
    textAlignVertical: 'center',
  },
  filterBtnStyle: {
    width: horizontalScale(50),
    height: verticalScale(50),
    backgroundColor: '#f6f6f6',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterImageStyle: {
    width: horizontalScale(22),
    height: verticalScale(22),
    transform: [{rotate: '270deg'}],
  },
  foodCateogoryView: {
    alignItems: 'center',
  },
  foodCategoryDirectionView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: horizontalScale(400),
    height: verticalScale(120),
    alignItems: 'center',
    marginTop: verticalScale(10),
  },
  foodCategoryImageStyle: {
    width: horizontalScale(60),
    height: horizontalScale(60),
  },
  foodCategoryText: {
    fontFamily: 'Poppins-Medium',
    fontSize: fontScale(14),
    marginTop: verticalScale(5),
  },
  lineBreakView: {
    width: horizontalScale(350),
    borderWidth: 2,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderColor: '#f0f0f0',
  },
  specialOfferStyle: {
    width: horizontalScale(350),
    height: verticalScale(50),
    marginTop: verticalScale(10),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backBtnStyle: {
    width: horizontalScale(28),
    height: verticalScale(28),
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 40,
    borderWidth: 1,
    borderColor: 'grey',
  },
  backImageStyle: {
    width: horizontalScale(15),
    height: verticalScale(15),
    transform: [{rotate: '180deg'}],
  },
  foodCategoryContent: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: verticalScale(17),
  },
  specialOfferView: {
    alignItems: 'center',
    marginTop: verticalScale(10),
  },
  specialOfferContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: horizontalScale(350),
  },
  specialOfferText: {
    fontFamily: 'Poppins-Medium',
    fontSize: verticalScale(15),
  },
  seeAllText: {
    color: 'green',
    fontFamily: 'Poppins-Medium',
    fontSize: verticalScale(15),
  },
  specialOfferStyleBanner: {
    alignItems: 'center',
    marginTop: verticalScale(10),
  },
  specialDealView: {
    alignItems: 'center',
    marginTop: verticalScale(7),
  },
  animatedViewImage: {
    width: horizontalScale(365),
    height: verticalScale(150),
    borderRadius: 20,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  indicatorView: {
    marginTop: verticalScale(20),
    flexDirection: 'row',
    alignSelf: 'center',
  },
  indicatorStyleView: {
    height: verticalScale(10),
    width: horizontalScale(10),
    borderRadius: 5,
    backgroundColor: '#33b056',
    marginHorizontal: 5,
  },
  topRatedView: {
    alignItems: 'center',
    marginTop: verticalScale(10),
  },
  topRatedDirection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: horizontalScale(350),
  },
  topRatedText: {
    fontFamily: 'Poppins-Medium',
    fontSize: verticalScale(16),
  },
  foodItemsView: {
    alignItems: 'center',
  },
  foodItemsStyle: {
    width: horizontalScale(160),
    height: verticalScale(200),
    backgroundColor: '#fffdf4',
    borderRadius: 10,
    alignItems: 'center',
    marginHorizontal: horizontalScale(10),
    marginVertical: verticalScale(10),
    borderWidth: 1,
    borderColor: '#d7f6d6',
  },
  heartIconStyle: {
    position: 'absolute',
    alignSelf: 'flex-end',
    right: horizontalScale(10),
    top: verticalScale(10),
  },
  imageBurgerStyle: {
    width: horizontalScale(80),
    height: verticalScale(80),
    marginTop: verticalScale(10),
  },
  foodNameItemsText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: verticalScale(14),
    marginTop: verticalScale(10),
  },
  foodBurgerText: {
    fontFamily: 'Poppins-Regular',
    fontSize: verticalScale(12),
    color: 'grey',
  },
  priceIncrementView: {
    marginTop: verticalScale(10),
  },
  priceIncrementDirection: {
    width: horizontalScale(140),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priceText: {
    fontFamily: 'Poppins-Regular',
    fontSize: verticalScale(14),
    color: 'green',
  },
  plusBtnStyle: {
    width: horizontalScale(30),
    height: verticalScale(30),
    backgroundColor: '#31af54',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
  },
  plusBtnText: {
    fontSize: verticalScale(21),
    fontFamily: 'Poppins-Medium',
    color: 'white',
  },
  topRatedFoodView: {
    alignItems: 'center',
  },
  topRatedFoodItems: {
    marginHorizontal: horizontalScale(10),
    marginVertical: verticalScale(10),
    borderColor: '#27282d',
    width: horizontalScale(110),
    height: verticalScale(130),
    backgroundColor: '#FEFBEB',
    borderRadius: 10,
    shadowColor: 'white',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 10,
    shadowRadius: 10,
    elevation: 5,
    zIndex: 1,
  },
  topRatedFoodContainerInside: {
    alignItems: 'center',
    bottom: verticalScale(10),
    overflow: 'hidden',
    zIndex: 2,
  },
  topRatedImageStyle: {
    width: horizontalScale(65),
    height: verticalScale(65),
  },
  ratedTextView: {
    alignItems: 'center',
  },
  ratedTextStyle: {
    fontFamily: 'Poppins-Medium',
    fontSize: verticalScale(13),
    bottom: verticalScale(5),
  },
  notificationDot: {
    position: 'absolute',
    overflow: 'visible',
    top: 5,
    right: 8,
    backgroundColor: 'green',
    width: 15,
    height: 15,
    borderRadius: 40,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  closeButton: {
    marginTop: 10,
    padding: 10,
    backgroundColor: 'green',
    borderRadius: 5,
  },
  closeButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  priceBtnSelectView: {
    alignItems: 'center',
  },
  priceBtnSelectStyle: {
    width: horizontalScale(75),
    height: verticalScale(25),
    backgroundColor: '#32AF55',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  priceBtnSelectText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: verticalScale(12),
    color: 'white',
  },
});

export default styles;